spring.application.name=library
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Vault Configuration (Teoretisk för Labb 1)
spring.cloud.vault.enabled=false
spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=my-root-token

spring.datasource.password=${vault:db-password}

spring.data.redis.host=localhost
spring.data.redis.port=6379
